version: "2"

run:
  timeout: 5m

linters:
  default: standard
  disable:
    - varnamelen
    - wsl
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0